## 1. Load Data

In [27]:
import pandas as pd

In [28]:
df = pd.read_csv("Cleaned Data/Merged.csv")

In [29]:
df.head()

,client_id,client_tenure_yr,client_tenure_month,client_age,gender,num_accts,balance,calls_6_mnth,logons_6_mnth,Variation
0,836976,6.0,73.0,60,Unknown,2,45105.30,6,9,Test
1,2304905,7.0,94.0,58,Unknown,2,110860.30,6,9,Control
2,1439522,5.0,64.0,32,Unknown,2,52467.79,6,9,Test
3,1562045,16.0,198.0,49,Male,2,67454.65,3,6,Test
4,5126305,12.0,145.0,33,Female,2,103671.75,0,3,Control

In [30]:
df['client_tenure_yr'].value_counts()

client_tenure_yr
6.0     5063
5.0     4950
7.0     3572
4.0     3381
15.0    3278
8.0     2919
14.0    2640
13.0    2586
12.0    2553
9.0     2363
10.0    2057
11.0    2051
16.0    1931
21.0    1560
20.0    1113
22.0    1066
17.0     977
23.0     924
18.0     868
19.0     821
24.0     597
26.0     487
27.0     467
28.0     367
25.0     340
3.0      337
29.0     224
30.0     217
33.0     144
32.0     122
31.0     116
34.0     115
35.0      73
2.0       61
37.0      29
36.0      27
38.0      23
48.0      12
40.0       7
39.0       7
46.0       5
47.0       5
55.0       5
50.0       4
43.0       4
49.0       4
42.0       4
51.0       3
44.0       2
54.0       1
41.0       1
45.0       1
52.0       1
Name: count, dtype: int64

In [31]:
df['client_age'].describe()

count    50485.000000
mean        47.323324
std         15.522202
min         17.000000
25%         34.000000
50%         48.000000
75%         60.000000
max         96.000000
Name: client_age, dtype: float64

In [32]:
df['gender'].value_counts()

gender
Unknown    17280
Male       16947
Female     16258
Name: count, dtype: int64

In [33]:
df['num_accts'].describe()

count    50485.000000
mean         2.254590
std          0.533683
min          1.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          7.000000
Name: num_accts, dtype: float64

## 2. Creating categories

In [53]:
df['age_group'] = pd.cut(
    df['client_age'],
    bins=[18, 34, 48, 60, 90],
    labels=['Young', 'Middle', 'Senior', 'Elders']
)

In [55]:
df['tenure_group'] = pd.cut(df['client_tenure_yr'],bins=[0,5,10,100],labels=['New','Mid','Long'])

In [56]:
df['tenure_group'].value_counts()

tenure_group
Long    25782
Mid     15974
New      8729
Name: count, dtype: int64

In [37]:
df.head()

,client_id,client_tenure_yr,client_tenure_month,client_age,gender,num_accts,balance,calls_6_mnth,logons_6_mnth,Variation,age_group,tenure_group
0,836976,6.0,73.0,60,Unknown,2,45105.30,6,9,Test,Senior,Mid
1,2304905,7.0,94.0,58,Unknown,2,110860.30,6,9,Control,Senior,Mid
2,1439522,5.0,64.0,32,Unknown,2,52467.79,6,9,Test,Young,New
3,1562045,16.0,198.0,49,Male,2,67454.65,3,6,Test,Senior,Long
4,5126305,12.0,145.0,33,Female,2,103671.75,0,3,Control,Young,Long

In [38]:
df['age_group'].value_counts()

age_group
Young     13872
Senior    13131
Middle    12027
Elders    11452
Name: count, dtype: int64

In [39]:
df['tenure_group'].value_counts()

tenure_group
Long    25782
Mid     15974
New      8729
Name: count, dtype: int64

Who are primary clients

In [40]:
df.groupby('age_group',observed=True)['logons_6_mnth'].sum()

age_group
Young     85273
Middle    70579
Senior    79752
Elders    73943
Name: logons_6_mnth, dtype: int64

In [41]:
df.groupby('age_group',observed=True)['calls_6_mnth'].sum()

age_group
Young     43362
Middle    34173
Senior    39850
Elders    38768
Name: calls_6_mnth, dtype: int64

Young clients are the most active users of the online process, while Middle aged  clients show slightly lower engagement. Young client use online as well as offline process more.

In [42]:
# Gender wise
df.groupby('gender')['logons_6_mnth'].sum()

gender
Female      95113
Male       109527
Unknown    104926
Name: logons_6_mnth, dtype: int64

In [43]:
(df['gender'].value_counts(normalize=True)*100).round(1)

gender
Unknown    34.2
Male       33.6
Female     32.2
Name: proportion, dtype: float64

Male usng online format are more as compared to women. Almost 1/3 rd the people do not wish to disclose their identity

In [44]:
#Tenure wise
df.groupby('tenure_group',observed=True)['logons_6_mnth'].sum()

tenure_group
New      53271
Mid      97623
Long    158672
Name: logons_6_mnth, dtype: int64

In [45]:
df.groupby('tenure_group',observed=True)['logons_6_mnth'].mean()

tenure_group
New     6.102761
Mid     6.111368
Long    6.154371
Name: logons_6_mnth, dtype: float64

Long term client tend to use online format more as compared to new client.

In [46]:
df['Variation'].value_counts()

Variation
Test       26959
Control    23526
Name: count, dtype: int64

In [47]:
#Variation wise
df.groupby('Variation')['logons_6_mnth'].mean()

Variation
Control    6.166242
Test       6.101821
Name: logons_6_mnth, dtype: float64

Both groups are equally active

In [48]:
df.groupby('balance')['logons_6_mnth'].sum()

balance
23789.44        3
23789.49        3
23789.54        3
23789.61        8
23789.72       11
               ..
8137343.24      9
8247729.97      4
8292996.21      9
8986419.77      9
16320040.15     9
Name: logons_6_mnth, Length: 50309, dtype: int64

In [49]:
df.groupby(pd.qcut(df['balance'], 4))['logons_6_mnth'].mean()

C:\Users\HP\AppData\Local\Temp\ipykernel_10568\533509868.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(pd.qcut(df['balance'], 4))['logons_6_mnth'].mean()

balance
(23789.439, 39880.48]       5.390350
(39880.48, 65736.8]         5.887965
(65736.8, 139961.96]        6.296807
(139961.96, 16320040.15]    6.952302
Name: logons_6_mnth, dtype: float64

People having higher balance login more as compared to other users.


## 2. Conclusions

1 Who are primary clients?

 Clients in the “Middle” and “Senior” age groups use the online process the most.

2 Younger or older?

 Older clients show higher usage compared to younger clients.

3 New or long-standing?

Long-standing clients are more active than new clients.

In [50]:
df.groupby(['Variation', 'age_group'])['logons_6_mnth'].mean()

C:\Users\HP\AppData\Local\Temp\ipykernel_10568\63218731.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['Variation', 'age_group'])['logons_6_mnth'].mean()

Variation  age_group
Control    Young        6.212870
           Middle       5.889764
           Senior       6.077485
           Elders       6.497419
Test       Young        6.091538
           Middle       5.849821
           Senior       6.070108
           Elders       6.420206
Name: logons_6_mnth, dtype: float64

In [51]:
df.groupby(['Variation', 'tenure_group'])['logons_6_mnth'].mean()

C:\Users\HP\AppData\Local\Temp\ipykernel_10568\2311036080.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['Variation', 'tenure_group'])['logons_6_mnth'].mean()

Variation  tenure_group
Control    New             6.129453
           Mid             6.154293
           Long            6.185625
Test       New             6.080329
           Mid             6.074247
           Long            6.126593
Name: logons_6_mnth, dtype: float64

In [52]:
df.groupby(['Variation', 'gender'])['logons_6_mnth'].mean()

Variation  gender
Control    Female     5.872845
           Male       6.493852
           Unknown    6.116546
Test       Female     5.830656
           Male       6.435446
           Unknown    6.033671
Name: logons_6_mnth, dtype: float64